"""
Django settings for EcommerceProject project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(oayg1)^d*1d^!*5g8hj@7ahgqjf5)lo5f+0yt%7(b7akh7xfi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ProdutosApp',
    'UsuariosCadastroApp',
    'HomeApp',
    'SobreApp',
    'MonteSeuComputadorApp',

    # apps de terceiros
    # 'notifications',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcommerceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcommerceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'templates/static'),)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



ACCESS_TOKEN_SERVER = "TEST-6261472583087320-030722-67cee6801b468dc3905e491f11041cf1-180251525"
ACCESS_TOKEN_CLIENT = "TEST-2cfc894d-c981-40c3-939b-2b706c7b731d"
MELHOR_ENVIO_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NTYiLCJqdGkiOiJhMmY4NjQxY2Y3NzkxYmY0ZWI5ZGU3ODQyZDUxZWYxMmZjMTBjYzVkYzI2OTA1N2Y1ZmMxYzE1Y2UzYTlkYjNlM2IwNDcwMjE2MmMzM2YyMyIsImlhdCI6MTcxMDg3OTM1MS42MDkzMjcsIm5iZiI6MTcxMDg3OTM1MS42MDkzMzEsImV4cCI6MTc0MjQxNTM1MS41OTYzNDMsInN1YiI6IjliOTljYzIyLWZlZDItNDM3My04ZTRhLTNjZDBmNmQxZmNjMiIsInNjb3BlcyI6WyJjYXJ0LXJlYWQiLCJjYXJ0LXdyaXRlIiwiY29tcGFuaWVzLXJlYWQiLCJjb21wYW5pZXMtd3JpdGUiLCJjb3Vwb25zLXJlYWQiLCJjb3Vwb25zLXdyaXRlIiwibm90aWZpY2F0aW9ucy1yZWFkIiwib3JkZXJzLXJlYWQiLCJwcm9kdWN0cy1yZWFkIiwicHJvZHVjdHMtZGVzdHJveSIsInByb2R1Y3RzLXdyaXRlIiwicHVyY2hhc2VzLXJlYWQiLCJzaGlwcGluZy1jYWxjdWxhdGUiLCJzaGlwcGluZy1jYW5jZWwiLCJzaGlwcGluZy1jaGVja291dCIsInNoaXBwaW5nLWNvbXBhbmllcyIsInNoaXBwaW5nLWdlbmVyYXRlIiwic2hpcHBpbmctcHJldmlldyIsInNoaXBwaW5nLXByaW50Iiwic2hpcHBpbmctc2hhcmUiLCJzaGlwcGluZy10cmFja2luZyIsImVjb21tZXJjZS1zaGlwcGluZyIsInRyYW5zYWN0aW9ucy1yZWFkIiwidXNlcnMtcmVhZCIsInVzZXJzLXdyaXRlIiwid2ViaG9va3MtcmVhZCIsIndlYmhvb2tzLXdyaXRlIiwid2ViaG9va3MtZGVsZXRlIiwidGRlYWxlci13ZWJob29rIl19.B5yhjNTw8k-hggMbe4VMgjOQSezsq78ymA3Z9gRQM0euPHtUFrpTotSogrj7BV1944VDFob7kUYwA2F3GsNu3xuwAdqtMfDhZ9hOF3Lg3xQwewt0qA3OfwEl6-3_fcdPWT4duE8B7EpGAfnJSwftOd7puDVKAqNXzIBscpNJNaU_Ia-lqko1RJrjg4RO2zOovrWeTyvgsDznBZQcVNSgfmV-9hVli_P1XW6HbrvrBUvJSHBKoeb3nV3xnPsmMPJRx9AAt5IYeW1v3RSsC7PduwKnszVci3PmuqkuvXT8cIhCh-8S49vScLxsSUIh_9IVN9yd8-bZNnCenUCE7vPqCGYNoyvThY5p2_vj6LwY7vxO3VdQ4s81VnjX_SPGlKjbVrqzL8k63kmrBMz5MVudbRntQKqbF0PohLbwO8jfcc3EzmU3KVRJZtqi30r31-pR0tbM86JSxNd5kbvJVufQNIi4Bmx9kSacWweOswvAGLaImKw2AnpAzYPi-tc5QV8HbdELoY6iuTv6TUMe6zrU9YFGWizNt-JBPafIpyujEd9-nBr3uZzjRuXoNmxP0bEbeTFKmGHMMVgp78uF33QtgWSgeuPSskIuLkWEWXQSBq7BF_vkvcCvxl_NKKTnP5S52xGuU8d73hDUoRNVwmNHLE9xZMb5Z_NYJ2N6WUw68Wo"